### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by rbs250** [vinitkumar/instabote#1]
Hi vinitkumar, thank you for such an awesome code!

I did everything as instructed, and all went smooth, but I get this error when I try to run the last command:

`Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.instabot import InstaBot
  File "C:\Users\****\Desktop\Github\instabote-master\src\instabot.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

Can you tell me what I'm doing wrong?
Thank you!!! 🙌🏻

**Comment by vinitkumar** [comment]
Sorry for typos I am writing this from phone.

From the error it seems like you don't have requests installed. Could you
please do

```
 pip install requests
```

That should fix the issues.

On 27-May-2017 3:46 PM, "rbs250" <notifications@github.com> wrote:

Hi vinitkumar, thank you for such an awesome code!

I did everything as instructed, and all went smooth, but I get this error
when I try to run the last command:

Traceback (most recent call last): File "main.py", line 1, in <module> from
src.instabot import InstaBot File "C:\Users\****\Desktop\Github\
instabote-master\src\instabot.py", line 8, in <module> import requests
ModuleNotFoundError: No module named 'requests'

Can you tell me what I'm doing wrong?
Thank you!!! 🙌🏻

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vinitkumar/instabote/issues/1>, or mute the thread

**Comment by rbs250** [comment]
Hi, Thanks for the quick reply, Ok so I installed the requests but now getting this:

`Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.instabot import InstaBot
  File "C:\Users\****\Desktop\Github\instabote-master\src\instabot.py", line 28, in <module>
    requests.packages.urllib3.disable_warnings()
AttributeError: module 'requests' has no attribute 'packages'`

Any suggestions?

Thanks a lot!

**Comment by vinitkumar** [comment]
Hi, back to my computer so I can't help out more. I see you are using Windows. Well, a couple of recommendations. Always use Virtualenvs for isolated Python environments that will not break anything else. In order to use Virtualenvs follow the tutorial here: https://virtualenv.pypa.io/en/stable/userguide/

To solve your current problem:

Try to do:

```
pip install -r requirements.txt
```

I have kept all the project requirements in this file, so this is a must for you to run this code.

Also, do you have Python3 installed? This project works on Python3. I recommend you install Python3.

**Comment by rbs250** [comment]
Hi, Thanks again!
So I ran the command, it installed all the requirements, but still I'm getting this:

`C:\Users\***\Desktop\Github\instabote-master>python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.instabot import InstaBot
  File "C:\Users\***\Desktop\Github\instabote-master\src\instabot.py", line 28, in <module>
    requests.packages.urllib3.disable_warnings()
AttributeError: module 'requests' has no attribute 'packages'`

My python versions is:
`C:\Users\***\Desktop\Github\instabote-master>python
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>`

I've been trying to follow the Virtualenvs guide, but since I'm a very very novice user with almost no programming background I'm encountering a lot of problems... :/ So I'll have to do some research I guess.

But thank you for the assistance!

**Comment by vinitkumar** [comment]
Do `pip freeze` and paste the result.

**Comment by rbs250** [comment]
```
certifi==2017.4.17
chardet==3.0.3
colorama==0.3.9
coverage==4.4.1
idna==2.5
mypy==0.511
py==1.4.33
pytest==3.1.0
pytest-cov==2.5.1
pyvmomi==6.5.0.2017.5.post1
PyYAML==3.12
requests==2.16.0
simplejson==3.10.0
six==1.10.0
typed-ast==1.0.3
urllib3==1.21.1
```

**Comment by vinitkumar** [comment]
Hi @rbs250 . I have frozen my dependencies. Please take a look at the latest code. https://github.com/vinitkumar/instabote/blob/master/requirements.txt and install these. It should just work then. Sorry, I don't have a windows machine so couldn't test it out before.

**Comment by rbs250** [comment]
Ok, Thanks a lot.
Now I get this:

`Collecting appdirs==1.4.2 (from -r requirements.txt (line 1))
  Using cached appdirs-1.4.2-py2.py3-none-any.whl
Collecting appnope==0.1.0 (from -r requirements.txt (line 2))
  Using cached appnope-0.1.0-py2.py3-none-any.whl
Collecting coverage==4.3.4 (from -r requirements.txt (line 3))
  Using cached coverage-4.3.4-cp36-cp36m-win_amd64.whl
Collecting decorator==4.0.11 (from -r requirements.txt (line 4))
  Using cached decorator-4.0.11-py2.py3-none-any.whl
Collecting gdata==2.0.18 (from -r requirements.txt (line 5))
  Using cached gdata-2.0.18.zip
Collecting instabote==1.0.0 (from -r requirements.txt (line 6))
  Could not find a version that satisfies the requirement instabote==1.0.0 (from -r requirements.txt (line 6)) (from versions: )
No matching distribution found for instabote==1.0.0 (from -r requirements.txt (line 6))`

And it stops there.

**Comment by vinitkumar** [comment]
Ah, my bad. Please check the latest and install again. I should not have added the library itself in the dependencies. `instabote==1.0.0` there. It should just work now.

**Comment by rbs250** [comment]
Thanks, Now it gets:

`Collecting py-boilerplate==1.0.0 (from -r requirements.txt (line 15))
  Could not find a version that satisfies the requirement py-boilerplate==1.0.0 (from -r requirements.txt (line 15)) (from versions: )
No matching distribution found for py-boilerplate==1.0.0 (from -r requirements.txt (line 15))`

**Comment by vinitkumar** [comment]
Remove the dependency and try again.

**Comment by rbs250** [comment]
It's working now.
I'll test it fully and will update for further documentation.

**Comment by vinitkumar** [comment]
Okay. I haven't tested much recently. Keep this issue open if you find any more problems. I am signing off for now. Have a good weekend.

**Comment by rbs250** [comment]
Thank you! :) 👍
